imports:
    - { resource: config_prod.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_staging.yml"
        strict_requirements: true

swiftmailer:
    delivery_address: vherrero@finderit.com
