fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

f_data_security:
    resource: "@FDataSecurityBundle/Resources/config/routing_staging.xml"
    prefix:   /

f_data_transactions:
    resource: "@FDataTransactionsBundle/Resources/config/routing.xml"
    prefix:   /


