security:
    providers:
        crm:
          id: f_data_security.user_provider

    encoders:
        crypt:
            algorithm: md5
            iterations: 0
            encode_as_base64: false
        plaintext:
            algorithm: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            pattern: ^/
            provider: crm
            form_login:
                check_path: /login_check
                login_path: /login
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path:   /logout

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_ADMIN, ROLE_CUENTA] }

